### ISSUE TITLE
Issue with 750g search

### ISSUE THREAD

**Issue by FabienNaour** [madeindjs/recipe_scraper#4]
Hi Alexandre,
I test your GEM with the following link on 750g:

                 url = 'http://www.750g.com/cote-de-boeuf-sweet-and-hot-r41872.htm'
                recipe = RecipeScraper::Recipe.new url

Unfortunatelly 'recipe' variable contains the following informations:

recipe: #<RecipeScraper::Recipe:0x00007fabe9a7c640 @title="Côte de boeuf sweet and hot", @preptime=0, @cooktime=0, @ingredients=[], @steps=[]>

@preptime, @cooktime, @ingredients, @steps are empty.
Thanks for your support
Fabien

**Comment by madeindjs** [comment]
Thank for your report. I just correct it and publish the 2.2.3 version. I think it will correct your problem. Can you confirm it?

**Comment by FabienNaour** [comment]
Hello Alexandre, it works , many thanks ! 
 is it possible for you to add a new field in recipe: "Nb de personnes"
Kind regards

**Comment by madeindjs** [comment]
Yes it is. Do you want to try to implement it yourself? I think it will be really easy to do it

**Comment by FabienNaour** [comment]
I'm junior dev but I can try

**Comment by madeindjs** [comment]
Bonjour Fabien,

C'est vraiment simple. Il suffit:
1. de forker et cloner le dépot
2. d'ajouter une propriété `attr_reader :nb_of_persons` à la classe `RecipeScraper::Recipe` dans le fichier _recipe_scraper/lib/recipe_scraper.rb_
3. d'ajouter un test dans le fihier _recipe_scraper/spec/recipe_750g_spec.rb_
4. de modifier la méthode [`RecipeScraper::Recipe#fetch_from_cuisineaz`](https://github.com/madeindjs/recipe_scraper/blob/master/lib/recipe_scraper.rb#L132) (pour CuisineAZ par ex) et de parser la balise HTML correspondante
5. lancer votre test avec `rake spec` et vérifier qu'il passe
6. faire une merge request

Dites-moi si ça vous semble faisable

**Comment by FabienNaour** [comment]
OK je me lance

**Comment by FabienNaour** [comment]
Bonjour Alexandre, j'ai effectué les modifs avec instanciation de nb_of_persons mais un PB apparait en executant le Rake de 750g (c'est OK pour Marmiton et cuisineAZ) : should GET picture (FAILED -1). Si tu es OK je fait un merge request et te laisse regarder. Merci

**Comment by madeindjs** [comment]
Nickel, ça me va. Merci

**Comment by FabienNaour** [comment]
c'est "mergé"

**Comment by madeindjs** [comment]
Nickel Fabien, l'erreur sur le test était "normale". Il s’agissait du cas lorsque la regex ne trouvait pas le bon nombre de personne. C'est corrigé par 43e5b0fcb55740749aa20ab6e502c3e43005261d .

Je viens de publier la version 2.2.4 sur https://rubygems.org, tu peux donc maintenant utiliser la nouvelle version.

Merci encore ;)

**Comment by FabienNaour** [comment]
Super ! Merci Alexandre . bon we
